[features]
seeds = false
skip-lint = false
skip-preflight = true
[programs.localnet]
todo = "9a43FDYE3S98dfN1rPAeavJT6MzBUEuF3bdX94zihQG2"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/shauh/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
