[features]
seeds = false
skip-lint = false
[programs.localnet]
tic_tac_toe = "9GigwZ232VNW38tZmMzeLJjo3yPbyDQ92LvhoKbKRTNB"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/shauh/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
